### ISSUE TITLE
Whitelist do not allow for expiry

### ISSUE THREAD

**Issue by jeff-cook** [arminc/clair-scanner#67]
My security team often asks that any exception has a built-in expiry date. A great example would be for a vulnerability that is not patched yet. So we can expect/whitelist the issue/vulnerability for 1 month, but we don't what to whitelist forever, or until manual review. 

An example of what an expire config might look like. 
```yaml
generalwhitelist:
  CVE-2017-6055: XML
    expire: 2019-02-03
  CVE-2017-5586: OpenText
images:
  ubuntu:
    CVE-2017-5230: Java
    CVE-2017-5230: XSX
  alpine:
    CVE-2017-3261: SE
```
